webtalk_init -webtalk_dir C:/Users/Andrea/source/repos/Andrea759/Uni_code/Digitale/LAB3/LAB3.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 14 16:21:09 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212091552_0_0_542" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "55964390-11b8-478a-8763-bd8b7e30edfd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d3902f139324482186fabab828bc8065" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1896 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8024_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1248258643 -regid "212091552_0_0_542" -xml C:/Users/Andrea/source/repos/Andrea759/Uni_code/Digitale/LAB3/LAB3.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Andrea/source/repos/Andrea759/Uni_code/Digitale/LAB3/LAB3.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Andrea/source/repos/Andrea759/Uni_code/Digitale/LAB3/LAB3.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
