webtalk_init -webtalk_dir /home/andre/src/Uni_code/Digitale/PWM/PWM.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 30 23:15:35 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1ee537ca-ccbc-4f5c-9257-9ec24191a4de" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "814d43ecd8854fb0ac74be4f6028d40b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Fedora" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Fedora release 35 (Thirty Five)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1900.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116224_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2768955445 -regid "" -xml /home/andre/src/Uni_code/Digitale/PWM/PWM.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/andre/src/Uni_code/Digitale/PWM/PWM.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/andre/src/Uni_code/Digitale/PWM/PWM.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
